#!/usr/bin/env python3
"""Generate a detailed, SLAM-friendly Gazebo Classic world: town_world.

The original slam_world is a bare plane + a handful of primitives, so the maps
come out sparse. This builds a structured "town": a textured ground, a grid of
varied-height/colored buildings separated by streets, corner landmarks for loop
closure, and a dense non-repetitive feature field so visual odometry stays
locked. All object tops are kept <= MAX_H so a drone flying the coverage path at
~2.5 m clears them.

Run:  python3 scripts/gen_world.py
Out:  ROS_2/src/drone_sim/worlds/town_world.world
"""
import os, random

random.seed(7)                      # deterministic world
MAX_H = 1.20                        # max object height (m); coverage flies at 2.5 m
OUT = os.path.join(os.path.dirname(__file__), "..",
                   "ROS_2/src/drone_sim/worlds/town_world.world")

# A varied palette so the true-color map is colorful and buildings are distinguishable.
PALETTE = [
    (0.80, 0.20, 0.20), (0.20, 0.55, 0.85), (0.90, 0.70, 0.15), (0.25, 0.65, 0.30),
    (0.60, 0.30, 0.70), (0.90, 0.45, 0.15), (0.30, 0.75, 0.75), (0.85, 0.40, 0.55),
    (0.50, 0.55, 0.60), (0.70, 0.75, 0.25),
]
# Discrete height tiers so the contour/height map reads as clean steps.
TIERS = [0.3, 0.5, 0.7, 0.9, 1.1]


def box(name, x, y, sx, sy, sz, rgb, yaw=0.0):
    r, g, b = rgb
    return (f'    <model name="{name}"><static>true</static>'
            f'<pose>{x:.2f} {y:.2f} {sz/2:.2f} 0 0 {yaw:.3f}</pose><link name="l">\n'
            f'      <collision name="c"><geometry><box><size>{sx:.2f} {sy:.2f} {sz:.2f}</size></box></geometry></collision>\n'
            f'      <visual name="v"><geometry><box><size>{sx:.2f} {sy:.2f} {sz:.2f}</size></box></geometry>\n'
            f'        <material><ambient>{r} {g} {b} 1</ambient><diffuse>{r} {g} {b} 1</diffuse></material></visual>\n'
            f'    </link></model>\n')


def cyl(name, x, y, rad, ln, rgb):
    r, g, b = rgb
    return (f'    <model name="{name}"><static>true</static>'
            f'<pose>{x:.2f} {y:.2f} {ln/2:.2f} 0 0 0</pose><link name="l">\n'
            f'      <collision name="c"><geometry><cylinder><radius>{rad:.2f}</radius><length>{ln:.2f}</length></cylinder></geometry></collision>\n'
            f'      <visual name="v"><geometry><cylinder><radius>{rad:.2f}</radius><length>{ln:.2f}</length></cylinder></geometry>\n'
            f'        <material><ambient>{r} {g} {b} 1</ambient><diffuse>{r} {g} {b} 1</diffuse></material></visual>\n'
            f'    </link></model>\n')


HEADER = '''<?xml version="1.0" ?>
<!--
  GENERATED by scripts/gen_world.py — edit the generator, not this file.

  A structured "town" for detailed RGB-D SLAM: textured ground + a grid of
  varied-height colored buildings on streets + corner landmarks + a dense
  feature field. Designed for the coverage_path flight (lawnmower @ ~2.5 m).
-->
<sdf version="1.6">
  <world name="town_world">

    <physics name="default_physics" default="0" type="ode">
      <gravity>0 0 -9.8066</gravity>
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
      <real_time_update_rate>250</real_time_update_rate>
    </physics>

    <plugin name="gazebo_ros_state" filename="libgazebo_ros_state.so">
      <ros><namespace>/gazebo</namespace></ros>
      <update_rate>50.0</update_rate>
    </plugin>

    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.7 0.8 0.9 1</background>
      <shadows>true</shadows>
    </scene>

    <light name="sun" type="directional">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.4 0.3 -0.9</direction>
    </light>

    <!-- textured ground: non-repetitive features for the downward camera -->
    <model name="ground_plane">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>60 60</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface>
        </collision>
        <visual name="visual">
          <cast_shadows>false</cast_shadows>
          <geometry><plane><normal>0 0 1</normal><size>60 60</size></plane></geometry>
          <material><script>
            <uri>file://media/materials/scripts/gazebo.material</uri>
            <name>Gazebo/CheckerBoard</name>
          </script></material>
        </visual>
      </link>
    </model>
'''

FOOTER = "  </world>\n</sdf>\n"


def occupied(x, y, keepout):
    """Keep a clear takeoff zone around the origin."""
    return (x * x + y * y) < keepout * keepout


def main():
    parts = [HEADER]

    # --- city blocks: buildings on a grid, streets in the gaps ----------------
    coords = [-10.5, -7.5, -4.5, -1.5, 1.5, 4.5, 7.5, 10.5]
    n = 0
    buildings = []
    for px in coords:
        for py in coords:
            if occupied(px, py, 2.2):        # clear zone for spawn/takeoff
                continue
            jx = px + random.uniform(-0.5, 0.5)
            jy = py + random.uniform(-0.5, 0.5)
            sx = random.uniform(0.8, 1.8)
            sy = random.uniform(0.8, 1.8)
            sz = random.choice(TIERS)
            rgb = random.choice(PALETTE)
            yaw = random.uniform(0, 1.57)
            parts.append(box(f"bld_{n}", jx, jy, sx, sy, sz, rgb, yaw))
            buildings.append((jx, jy))
            n += 1

    # --- corner landmarks (distinct, tallest allowed) for loop closure --------
    for i, (lx, ly) in enumerate([(-12, -12), (12, -12), (12, 12), (-12, 12)]):
        parts.append(cyl(f"landmark_{i}", lx, ly, 0.45, MAX_H, PALETTE[i]))

    # --- a few cylinders (tanks/trees) for shape variety ----------------------
    for i in range(10):
        cx, cy = random.uniform(-11, 11), random.uniform(-11, 11)
        if occupied(cx, cy, 2.2):
            continue
        parts.append(cyl(f"tank_{i}", cx, cy, random.uniform(0.3, 0.5),
                         random.choice(TIERS), random.choice(PALETTE)))

    # --- dense non-repetitive feature field on the ground (VO lock) -----------
    for i in range(220):
        fx, fy = random.uniform(-13, 13), random.uniform(-13, 13)
        s = random.uniform(0.15, 0.35)
        g = random.uniform(0.25, 0.85)
        rgb = (g, g * random.uniform(0.8, 1.0), g * random.uniform(0.8, 1.0))
        parts.append(box(f"ft_{i}", fx, fy, s, s, 0.04, rgb, random.uniform(0, 1.57)))

    parts.append(FOOTER)
    with open(OUT, "w") as f:
        f.write("".join(parts))
    print(f"wrote {os.path.normpath(OUT)}")
    print(f"  {n} buildings, 4 landmarks, ~10 tanks, 220 feature tiles "
          f"(all <= {MAX_H} m tall)")


if __name__ == "__main__":
    main()
